apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: sahakanush224/goapp:0.1.0
          name: web
          ports:
          - containerPort: 8097
            name: web
            protocol: TCP
