apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: sahakanush224/web:93a82a60a01248c634d7ebb101bc60128c3aecfd
        name: web
        ports:
        - containerPort: 8097
          name: web
          protocol: TCP
