name: configuration

on:
   push:
   
jobs:    
  Tag_operations:
    runs-on: ubuntu-latest 
    
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
      
    steps:           
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
        
      - 
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}
          
      -
        name: Create tag
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          append_to_pre_release_tag: RC
          tag_prefix: ''     
          
      - 
        run: echo "git_tag=${{steps.tag_version.outputs.new_version}}" >> $GITHUB_ENV
        
      - 
        name: Get tag
        id: get_tag
        run: echo "::set-output name=tag::${{env.git_tag}}"
        
  Docker_operations:
    runs-on: ubuntu-latest    
    needs: Tag_operations
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
        
      - 
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}          
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:${{needs.Tag_operations.outputs.tag}}
          
  Change_manifest_image:
    runs-on: ubuntu-latest     
    needs: [Tag_operations, Docker_operations]
    
    steps:
      - 
        name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
        
      - 
        name: Check out other repo
        uses: actions/checkout@master
        with:
          repository: FastCook2/ArgoApps
          path: ./
          token: ${{ secrets.GIT_TOKEN }}
          
      - 
        name: Clone application repo        
        run: |
          git clone --branch  ${{ steps.branch-name.outputs.current_branch }} https://Sahakanush:${{ secrets.GIT_TOKEN }}@github.com/Sahakanush/demo
          cd demo
          echo "git_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - 
        name: Change tag 
        working-directory: demo/.github/
        run: |    
          python3 change_tag.py ${{ secrets.DOCKERHUB_USERNAME }}/demo:${{needs.Tag_operations.outputs.tag}}
      -
        name: Push new image to GitHub
        working-directory: ./
        run: |
          git config --global user.name "sahakanush"
          git config --global user.email "sahakanush.terteryan2003@gmail.com"
          
          git add ArgoApps/app.yaml
          git commit -m "Change Tag"
          git push
