name: configuration

on:
   push:
env:
   github: ${{toJson(github.sha)}} 
jobs:    
   
  
  Docker_operations:
    runs-on: ubuntu-latest
    steps:
      
      - 
        name: Checkout repository
        uses: actions/checkout@v3
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:$github
          
  Change_manifest_image:
    runs-on: ubuntu-latest     
    needs: [Docker_operations]
    
    steps:    
      - 
        name: Clone application repo        
        run: |
          git clone https://armenmelkonyan90:${{ secrets.GIT_TOKEN }}@github.com/armenmelkonyan90/demo

      - 
        name: Change tag 
        working-directory: demo/.github/
        run: |    
          python3 change_tag.py ${{ secrets.DOCKERHUB_USERNAME }}/demo:$github
      -
        name: Push new image to GitHub
        working-directory: ./demo
        run: |
          git config --global user.name "example"
          git config --global user.email "example@gmail.com"
          
          git add ArgoApps/app.yaml
          git commit -m "Change Tag"
          git push
